version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo IMAGE_TAG - $IMAGE_TAG
      - REPO_URL=$ECR_URL/rb2019

  build:
    commands:
      - echo Start Docker image...
      - docker build -t $REPO_URL:latest .
      - docker tag $REPO_URL:latest $REPO_URL:$IMAGE_TAG
      - echo End Docker image...

  post_build:
    commands:
      - echo Start pushing Docker image...
      - docker push $REPO_URL
      - echo End pushing Docker image...
